/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes2;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.*;
import java.lang.reflect.Type;
import java.net.Proxy;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        System.out.println("Author Name >>>>>>>"+getData().author+"<<<<<<<<");
        System.out.println("Text >>>>>>>"+getData().text);
//        System.out.println(getData());
    }

    static Quote getData(){
        String path="C:\\java-projects\\quotes2\\app\\src\\main\\resources\\recentquotes.json";
        File file=new File(path);
       StringBuilder stringBuilder=new StringBuilder();


            try {
                BufferedReader bufferedReader=new BufferedReader(new FileReader(file));
                int theCharNum=bufferedReader.read();
                while (theCharNum!= -1){
                    char theChar = (char) theCharNum;

                    stringBuilder.append(theChar);

                    theCharNum = bufferedReader.read();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
//            System.out.println(stringBuilder);

            Gson gson = new Gson();

            // Other way
//            Type type = new TypeToken<ArrayList<Quote>>(){}.getType();
//            System.out.println(type.getTypeName())
//            ArrayList<Quote> list1 = gson.fromJson(stringBuilder.toString(),type);
//
        Quote[] list = gson.fromJson(stringBuilder.toString(),Quote[].class);
        System.out.println(Quote[].class);
//            System.out.println(list);
            int index= (int) (Math.random() * (list.length + 1) + 0);
        Quote quote=list[index];

    return quote;
    }



}
